language: python
python:
  - "2.7"
  - "3.5"

branches:
  only: 
    - master

install:
  - if [ -f ${PROJECT}/requirements.txt ]; then pip install -r ${PROJECT}/requirements.txt ; fi
  - pip install flake8

script: flake8 ${PROJECT} --show-source --statistics
